### ISSUE TITLE
ddsmraw2pnm.exe under linux

### ISSUE THREAD

**Issue by kumkee** [multinormal/ddsm#1]
I can verify that jpeg is running properly in my linux box, but ddsmraw2pnm.exe is not.
Do I need the latter?
I also found ./jpeg.exe in the ruby code. Do I need to change it to ./jpeg for linux systems?

**Comment by kumkee** [comment]
Did you really try the whole thing under 64bit linux?
Apart from not being able to run ddsmraw2pnm.exe, I can't run it with wine neither. It requires cygwin library!
Just imagine cygwin with wine.....

**Comment by baptist** [comment]
Same problem..

**Comment by multinormal** [comment]
I've just added the source for ddsmraw2pnm — apologies this was omitted. Please note you'll need to compile this manually (see the source), and the Ruby code will need to be modified to choose the correct binary depending on platform. I'm afraid I don't work on digital mammography any more, but I do welcome pull requests!
